# Generated by Django 2.0.6 on 2018-06-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
        ('job_orders', '0002_joborder_cmplt_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_partial_status', models.CharField(choices=[('In_process', 'En proceso'), ('Closed', 'Cerrada')], default='In_process', max_length=12)),
                ('packaged_qty', models.IntegerField(blank=True, null=True)),
                ('retention_samples_qty', models.IntegerField(blank=True, null=True)),
                ('reworked_qty', models.IntegerField(blank=True, null=True)),
                ('q_issues_qty', models.IntegerField(blank=True, null=True)),
                ('rejected_qty', models.IntegerField(blank=True, null=True)),
                ('total_qty', models.IntegerField(blank=True, null=True)),
                ('first_pass_qty', models.IntegerField(blank=True, null=True)),
                ('job_process_time', models.FloatField(blank=True, null=True)),
                ('planned_downtime', models.FloatField(blank=True, null=True)),
                ('not_planned_downtime', models.FloatField(blank=True, null=True)),
                ('job_performance_comments', models.TextField(blank=True, null=True)),
                ('job_quality_comments', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('close_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_number_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='JobOrderData_job_order', to='job_orders.JobOrder')),
                ('shift_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='JobOrderData_shift', to='shifts.Shift')),
            ],
        ),
    ]
