# Generated by Django 2.0.6 on 2018-06-27 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_orders_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joborderdata',
            old_name='job_number_id',
            new_name='job_order',
        ),
        migrations.RenameField(
            model_name='joborderdata',
            old_name='shift_id',
            new_name='shift',
        ),
        migrations.AlterField(
            model_name='joborderdata',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='joborderdata_workstation', to='workstations.Workstation'),
        ),
    ]
