# Generated by Django 2.0.6 on 2018-06-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_orders_data', '0002_auto_20180620_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborderdata',
            name='first_pass_qty',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='joborderdata',
            name='planned_downtime',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='joborderdata',
            name='q_issues_qty',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='joborderdata',
            name='rejected_qty',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='joborderdata',
            name='reworked_qty',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='joborderdata',
            name='total_qty',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
