# Generated by Django 2.0.6 on 2018-06-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_orders_data', '0003_auto_20180625_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborderdata',
            name='job_process_time',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='joborderdata',
            name='not_planned_downtime',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
