# Generated by Django 2.0.6 on 2018-06-25 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workstations', '0003_auto_20180619_1707'),
        ('job_orders_data', '0004_auto_20180625_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborderdata',
            name='workstation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='joborderdata_workstation', to='workstations.Workstation'),
        ),
    ]
