# Generated by Django 2.0.6 on 2018-06-25 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_auto_20180610_0407'),
        ('job_orders', '0003_auto_20180625_1316'),
        ('workstations', '0003_auto_20180619_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_detail_status', models.CharField(choices=[('Created', 'Creada'), ('Planned', 'Planificada'), ('In_process', 'En proceso'), ('Closed', 'Cerrada'), ('Canceled', 'Cancelada')], default='In_process', max_length=12)),
                ('production_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='joborderdetail_item', to='items.Item')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='joborderdetail_job_order', to='job_orders.JobOrder')),
                ('workstation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='joborderdetail_workstation', to='workstations.Workstation')),
            ],
        ),
    ]
