# Generated by Django 2.0.6 on 2018-06-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_orders_detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joborderdetail',
            old_name='job_order_id',
            new_name='job_order',
        ),
    ]
