# Generated by Django 2.0.6 on 2018-06-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_orders_detail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joborderdetail',
            name='job_detail_status',
        ),
        migrations.AlterField(
            model_name='joborderdetail',
            name='job_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
