# Generated by Django 2.0.6 on 2018-06-26 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_orders_detail', '0002_auto_20180626_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joborderdetail',
            old_name='job_order',
            new_name='job_order_id',
        ),
    ]
