# Generated by Django 2.0.6 on 2018-06-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=10)),
                ('planned_qty', models.IntegerField(default=1)),
                ('cmplt_qty', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('job_status', models.CharField(choices=[('Created', 'Creada'), ('Planned', 'Planificada'), ('In_process', 'En proceso'), ('Closed', 'Cerrada'), ('Canceled', 'Cancelada')], default='Created', max_length=12)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('close_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='joborder_item', to='items.Item')),
            ],
        ),
    ]
