# Generated by Django 2.0.6 on 2018-06-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='cmplt_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
