# Generated by Django 2.0.6 on 2018-06-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_orders', '0002_joborder_cmplt_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joborder',
            old_name='item_id',
            new_name='item',
        ),
    ]
