# Generated by Django 2.0.6 on 2018-06-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='stop_res_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
