# Generated by Django 2.0.6 on 2018-06-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0002_stop_stop_res_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='stop_type',
            field=models.CharField(choices=[('NPSTOP', 'Parada no planificada'), ('PSTOP', 'Parada planificada')], max_length=6),
        ),
    ]
