# Generated by Django 2.0.6 on 2018-06-11 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workstations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='ws_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant', to='plants.Plant'),
        ),
    ]
