# Generated by Django 2.0.6 on 2018-06-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workstations', '0002_auto_20180611_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='ws_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstation_plant', to='plants.Plant'),
        ),
    ]
