# Generated by Django 2.0.6 on 2018-06-25 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_stops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstop',
            name='stop_type',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='jobstop',
            name='job_order_data_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobstop_job_order_data', to='job_orders_data.JobOrderData'),
        ),
        migrations.AlterField(
            model_name='jobstop',
            name='stop_time',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
