# Generated by Django 2.0.6 on 2018-06-11 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workstations', '0002_auto_20180611_0502'),
        ('items', '0002_auto_20180610_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='items.Item')),
                ('workstation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstation', to='workstations.Workstation')),
            ],
        ),
    ]
