# Generated by Django 2.0.6 on 2018-06-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='production_rate',
            field=models.FloatField(default=0),
        ),
    ]
