# Generated by Django 2.0.6 on 2018-06-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_bom_production_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_item', to='items.Item'),
        ),
    ]
